### ISSUE TITLE
KeyboardInterrupt not causing handle_request to exit when using blocking call.

### ISSUE THREAD

**Issue by laundmo** [lona-web-org/lona#191] opened 2022-01-14 22:13 UTC
When using a blocking call in the handle_request of a view, KeyboardInterrupt does not cause it to stop.

I initially discovered this trying to write a view that updates with items from a Queue, where it hang on `queue.get()` inside the handle_request, but the same applies to time.sleep()

Minimal Example:
```py
import time
from lona import LonaView, LonaApp

app = LonaApp(__file__)

@app.route('/')
class Test(LonaView):
    def handle_request(self, request):
        time.sleep(100000)

app.run(port=8080)
```

OS: Windows 10
Python: 3.9.0
Lona: 1.8.5

**Comment by fscherf** [comment] 2022-01-15 08:36
Hi @laundmo,

the problem here is that keyboard interrupt gets handled by the main thread but ``handle_request`` runs in its own thread. There is no simple way in python (that i know of) to cancel all threads. 
The best way to deal with this kind of problems are periodic timeouts or using the ioloop for sleeping like ``lona.LonaView.sleep`` https://lona-web.org/end-user-documentation/views.html#lonaview-sleep-args-kwargs

**Comment by laundmo** [comment] 2022-01-15 12:56
Could you perhaps use Daemon threads, so they will be killed when the main process tries to exit?

from the threading daemon docs:
> The entire Python program exits when no alive non-daemon threads are left.

**Comment by fscherf** [comment] 2022-01-15 13:55
@laundmo that might be a good idea. I tried mark all threads as daemon threads, but this does not seem to be enough: ``handle_request()`` always continue to run after i hit ``CTRL-c``

**Comment by laundmo** [comment] 2022-01-15 14:00
with a brief look in the code i can see Lona uses ThreadPoolExecutor, which doesn't really make daemon threads according to this issue
https://stackoverflow.com/questions/49992329/the-workers-in-threadpoolexecutor-is-not-really-daemon

**Comment by fscherf** [comment] 2022-01-15 14:02
Yes i know. i patched ``daemon=True`` into the standard library to test this

**Comment by laundmo** [comment] 2022-01-15 16:05
very dirty way to do this would be to call os._exit() somewhere
but that will exit instantly without any cleanup. a better approach might be to have a flag that stops the threads from the inside.

**Comment by fscherf** [comment] 2022-01-15 16:32
Yes that seems pretty dirty (but would work)

The thread would have to be compliant then though. If it just runs ``time.sleep(1000000)`` the server can't stop. 

Have you seen this: https://lona-web.org/end-user-documentation/views.html#lonaview-ping ? 
If called periodically by the thread, it gets stopped when the server stops.

**Comment by laundmo** [comment] 2022-01-15 20:59
yeah my solution ended up being similar to this, by using get_nowait on the queue and sleeping for .01 secs. Still, kinda annoying that concurrent.futures cant handle that.

**Comment by fscherf** [comment] 2022-01-16 13:14
I agree. I think there is nothig we can do about this here. Maybe some documentation

**Comment by fscherf** [comment] 2022-01-19 18:48
@laundmo i did some experimentation and you are right: the daemon flag would fix this problem. We would have to stop using ``concurrent.futures.ThreadPoolExecutor``, but that should be no problem.

This fix would raise another problem: Currently a view can decide to not shut down immediately to commit a database transaction or close a file for example. We would need to make the daemon flag configurable (maybe even per view).

**Comment by fscherf** [comment] 2022-02-19 14:09
I thought a lot about this issue. We have to consider: Is this a bug or a feature? Lona has all API to make views compliant to immediate shutdown via ``CTRL-C``. Maybe a user has good reasons to not do so.

This behavior is caused by the implementation of the ``ThreadPoolExecutor`` in the standard library. One could argue that this is the behavior user expect, programming Python multi-threaded.

@maratori, @korantu, @sobolevn: Any thougts?

**Comment by maratori** [comment] 2022-02-22 20:38
I don't know if it's real to change Lona to support following or not. But the best behaviour I can imagine is a graceful shutdown with some timeout.

What does it mean?
When the app receives signal (for example Ctrl+C), it stops receiving new requests and waits for current requests finish. If they don't finish in some timeout the app exits even if there are some DB queries are in progress.
It allows to close the app in the most gentle way.

I know how to easily do it in Golang, but don't know about Python.

**Comment by fscherf** [comment] 2022-05-09 17:42
@laundmo: I did some experimenting with a custom threadpool executor. Its absolutely possible to design one that shuts down immediately when you hit ctrl-c. I don't think we should something like this though.
The current behavior is the default behavior of any multithreated python application, and I think most developers will expect lona to behave like this. If fast shutdown is a concern for a view, it can use `server.ping()` to check if the server want's to shut down.

**Comment by fscherf** [comment] 2022-10-31 18:19
@laundmo: what's your opinion on this?

**Comment by fscherf** [comment] 2022-11-14 14:48
I will close this issue for now. Feel free to reopen it if you want to discuss this issue further

**Closed by fscherf** 2022-11-14 14:48 UTC
Labels: enhancement
